### ISSUE TITLE
Add ability to transfer ownership of an idea

### ISSUE THREAD

**Issue by SimonCropp** [Code52/Ideastrike#75]

**Comment by alexbeletsky** [comment]
Nice featuture, I would like to participate. But scenario should be groomed, I can see different way of implementations.

**Comment by shiftkey** [comment]
Lets start with a mockup of the UI 
- where should this live on the idea page?
- how do i select a user (auto-complete form?) 
- what steps do the owner and the new owner need to do as part of the "workflow"?
- what about the opposite scenario - can a user take over an idea? what sort of reasons can you think of?
