### ISSUE TITLE
Sign in doesn't work with Internet Explorer 9

### ISSUE THREAD

**Issue by mikoskinen** [Code52/Ideastrike#77]
Signing in to Ideastrike doesn't work with IE9. It works correctly with Chrome.

When the Sign In link is clicked, the Sign in popup opens, but when a provider is selected and the user authenticates, the Ideastrike's JavaScript causes the following error:

Microsoft JScript runtime error: Unable to get value of the property 'closed': object is null or undefined

In Engage Auth Widget:
{if(a&&a.closed||typeof a.closed==="undefined")

**Comment by ghost** [comment]
It looks to be a bug with running it locally with RpxNow, not us as such. You can try logging in just fine on http://ideastrike.apphb.com/
