### ISSUE TITLE
Bootstrap.min does not contain classes for errors?

### ISSUE THREAD

**Issue by alexbeletsky** [Code52/Ideastrike#82]
I was a little surprised, but found out that version of bootrap included to IdeaStrike, does not contain classes to be applied to inputs/texts-areas in case they are in invalid state.

Why is that? It that some limitations of .min version? I believe we should add those, for better validation and interactivity;

**Comment by andrewtobin** [comment]
Hey Alexander,

That's not entirely true, the issue with version 1.4 of Bootstrap is that it needs to be applied to the parent div so it applies to both the label and the input, like so: 

```
    <div class="clearfix error">
        <label for="Title">Title</label>
        <div class="input">
            <input id="Title" name="Title" type="text"/>
        </div>
    </div>
```

Unfortunately they've done a major upgrade to Bootstrap so pointing you at the documentation it's not as clear as I would hope (and would have been nice for them to archive somewhere) but it is pretty clear from reading the css.

If you look at the new version and read source, then search for "error" you'll see they have renamed the clearfix to control-group but they still apply the error at the group level.

Yes, this is different wording to how they do it in MVC (and in my nuget package I actually override the built in MVC aliases to the bootstrap so you can just scaffold it).

So to answer you, it is not a limitation, but their way of expanding what is covered by the warning to both the label and the input, and you may need to put an id on the div so you know which div applies to which input - hope that helps.

Andrew

**Comment by alexbeletsky** [comment]
ohh - .clearfix.error - now it explain everything :)

Thanks for that info!
