### ISSUE TITLE
Repository contains AppHarbor DB password

### ISSUE THREAD

**Issue by maximz** [Code52/Ideastrike#85]
While the AppHarbor install is only meant to be temporary and for testing, its database connection details are completely exposed in [Web.release.config](https://github.com/Code52/Ideastrike/blob/master/src/Ideastrike.Nancy/Web.Release.config).

I'm not familiar with how AppHarbor works, but in any case, exposing passwords like this is probably not safe.

Thoughts?

**Comment by ghost** [comment]
For the purpose of rapid dev, it was just easier to have it in there than fight to get AppHb to work with us right.

Before we go "live", we'll be regenerating the password and removing it from the config so that AppHb injects it correctly.
